version: "3.9"
services:
  app:
    build: .
    ports:
      - "80:3000"
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: "user"
      POSTGRES_DB: "tuanhuydev"
