export const UserPermissions = {
  VIEW_PROJECT: "VIEW_PROJECT",
  CREATE_PROJECT: "CREATE_PROJECT",
  DELETE_PROJECT: "DELETE_PROJECT",
  UPDATE_PROJECT: "UPDATE_PROJECT",

  VIEW_TASK: "VIEW_TASK",
  CREATE_TASK: "CREATE_TASK",
  DELETE_TASK: "DELETE_TASK",
  UPDATE_TASK: "UPDATE_TASK",

  VIEW_POST: "VIEW_POST",
  CREATE_POST: "CREATE_POST",
  DELETE_POST: "DELETE_POST",
  UPDATE_POST: "UPDATE_POST",

  VIEW_USER: "VIEW_USER",
  CREATE_USER: "CREATE_USER",
  DELETE_USER: "DELETE_USER",
  UPDATE_USER: "UPDATE_USER",

  VIEW_SETTING: "VIEW_SETTING",
  UPDATE_SETTING: "UPDATE_SETTING",
};
