export const HTTP_CODE = {
  SUCCESS: 200,
  INTERNAL_ERROR: 500,
  NOT_FOUND_ERROR: 404,
  UNAUTHORIZED_ERROR: 401,
  BAD_REQUEST_ERROR: 400,
  METHOD_NOT_ALLOWED_ERROR: 405,
};

export type HttpCodeType = typeof HTTP_CODE;
