export const Permissions = {
  VIEW_PROJECTS: "VIEW_PROJECTS",
  CREATE_PROJECT: "CREATE_PROJECT",
  EDIT_PROJECT: "EDIT_PROJECT",
  DELETE_PROJECT: "DELETE_PROJECT",
  UPDATE_PROJECT: "UPDATE_PROJECT",

  VIEW_TASKS: "VIEW_TASKS",
  CREATE_TASK: "CREATE_TASK",
  EDIT_TASK: "EDIT_TASK",
  DELETE_TASK: "DELETE_TASK",
  UPDATE_TASK: "UPDATE_TASK",

  VIEW_POSTS: "VIEW_POSTS",
  CREATE_POST: "CREATE_POST",
  EDIT_POST: "EDIT_POST",
  DELETE_POST: "DELETE_POST",
  UPDATE_POST: "UPDATE_POST",

  VIEW_USERS: "VIEW_USERS",
  CREATE_USER: "CREATE_USER",
  EDIT_USER: "EDIT_USER",
  DELETE_USER: "DELETE_USER",
  UPDATE_USER: "UPDATE_USER",

  VIEW_SETTINGS: "VIEW_SETTINGS",
  UPDATE_SETTINGS: "UPDATE_SETTINGS",
};
