name: tuanhuy.dev CD
on:
  push:
    branches: [main]
jobs:
  release:
    name: Release new tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: tuanhuydev/tuanhuydev
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install Dependencies
        run: npm install
      
      - name: Setup git credential
        run: |
          git config --global user.name 'tuanhuydev'
          git config --global user.email 'tuanhuydev@gmail.com'

      # - name: Release version
      #   run: npm run release:major

      # - name: Push to origin
      #   run: | 
      #     echo "The current branch is ${GITHUB_REF##*/}"
      #     git push --follow-tags origin ${GITHUB_REF##*/}

      # - name: Push tag to GitHub
      #   run: git push --follow-tags origin ${GITHUB_REF##*/}
  build:
    if: github.event.pull_request.merged == true
    name: Docker build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Login to Dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tuanhuydev:latest
