name: tuanhuy.dev CI
on: 
  push:
jobs:
  commitlint:
    name: Validate Commit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install required dependencies
        run: |
          npm install
          git -v
          npx commitlint -v

      - name: Validate current commit
        run: npx commitlint --from HEAD~1 --to HEAD --verbose
  test:
    runs-on: ubuntu-latest
    name: Run test suits
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install required dependencies
        run: npm install
      - name: Generate prisma client
        run: npm run db:generate
      - name: Run test suites
        run: npm run test
