name: Deploy to Stagging
on:
  pull_request:
    types:
      - closed
    branches:
      - dev
permissions:
  id-token: write
  contents: read
jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Login to Dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tuanhuydev:latest
          push: true
          secrets: |
            "GOOGLE_ADSENSE=${{ secrets.GOOGLE_ADSENSE }}"
            "GOOGLE_TAG=${{ secrets.GOOGLE_TAG }}"
            "AWS_REGION=${{ secrets.AWS_REGION }}"
            "DATABASE_URL=${{ secrets.DATABASE_URL }}"
          

  # deploy:
  #   name: Connect and Deploy AWS
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3

  #     - name: Connect AWS
  #       uses: aws-actions/configure-aws-credentials@v2
  #       with:
  #         role-to-assume: ${{ secrets.AWS_ACTION_ROLE }}
  #         aws-region: ${{ secrets.AWS_REGION }}
  #         role-session-name: GithubActionSession
      
  #     - name: Stop running containers
  #       run: |
  #         aws ecs update-service --cluster tuanhuydev --service tuanhuydev-service --desired-count 0
  #         sleep 60

  #     - name: Deploy Amazon ECS task definition
  #       uses: aws-actions/amazon-ecs-deploy-task-definition@v1
  #       with:
  #         task-definition: lib/backend/.aws/task-definition.json
  #         service: tuanhuydev-service
  #         cluster: tuanhuydev
  #         wait-for-service-stability: true

      